server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EzerbelCN/springcloud-config #github上仓库的名字
          search-paths:
            - springcloud-config/configs
          username: EzerbelCN@gmail.com
          password: 1!QazxsW2@3#Edc
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka